AWSTemplateFormatVersion: '2010-09-09'
Description: 'Netskope Private Access Publisher Deployment'

Parameters:
  InstanceName:
    Type: String
    Description: "Name for the instance"
  
  KeyPairName:
    Type: String
    Description: "Name of existing EC2 KeyPair"
  
  InstanceType:
    Type: String
    AllowedValues:
      - "t3.medium"
      - "t3.large"
    Description: "EC2 instance type"
  
  VpcId:
    Type: String
    Description: "VPC ID"
  
  SubnetId:
    Type: String
    Description: "Subnet ID"
  
  TenantUrl:
    Type: String
    NoEcho: true
    Description: "Netskope tenant URL (e.g., yourtenant.goskope.com)"
  
  ApiToken:
    Type: String
    NoEcho: true
    Description: "Netskope API token"
  
  PublisherTag:
    Type: String
    Description: "Optional publisher tag"
  
  PublisherUpgrade:
    Type: String
    Description: "Publisher upgrade profile"
  
  InstanceCount:
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 8
    Description: "Number of publisher instances to deploy"

Resources:
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: 
                  - arn:aws:s3:::ztnatemplate/nsk-deployment.sh

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
        - !Ref EC2Role

  NetskopeSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Netskope Publisher
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${InstanceName}-sg

  NetskopeInstanceTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub ${InstanceName}-launch-template
      LaunchTemplateData:
        ImageId: ami-06d48250a66f3d72f
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyPairName
        IamInstanceProfile:
          Name: !Ref EC2InstanceProfile
        SecurityGroupIds: 
          - !Ref NetskopeSecurityGroup
        BlockDeviceMappings:
          - DeviceName: /dev/sda1
            Ebs:
              VolumeSize: 64
              VolumeType: gp3
              DeleteOnTermination: true
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            # Set up logging
            exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
            
            echo "Starting user data script execution..."
            
            # Install required packages first
            apt-get update
            apt-get install -y curl awscli
            
            # Get instance ID and set hostname
            INSTANCE_ID=`curl -s http://169.254.169.254/latest/meta-data/instance-id`
            HOSTNAME="${InstanceName}-$INSTANCE_ID"
            hostnamectl set-hostname "$HOSTNAME"
            
            # Update /etc/hosts to prevent sudo warnings
            echo "127.0.0.1 $HOSTNAME" >> /etc/hosts

            # Download the deployment script from S3
            aws s3 cp s3://ztnatemplate/nsk-deployment.sh /usr/local/bin/run-publisher-setup.sh
            chmod 755 /usr/local/bin/run-publisher-setup.sh

            # Update the script with variables
            sed -i "s/##TENANT_URL##/${TenantUrl}/g" /usr/local/bin/run-publisher-setup.sh
            sed -i "s/##API_TOKEN##/${ApiToken}/g" /usr/local/bin/run-publisher-setup.sh
            sed -i "s/##PUB_TAG##/${PublisherTag}/g" /usr/local/bin/run-publisher-setup.sh
            sed -i "s/##PUB_UPGRADE##/${PublisherUpgrade}/g" /usr/local/bin/run-publisher-setup.sh

            # Run the setup script in background
            systemd-run --no-block /usr/local/bin/run-publisher-setup.sh
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value: !Sub ${InstanceName}

  NetskopeAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub ${InstanceName}-asg
      VPCZoneIdentifier:
        - !Ref SubnetId
      LaunchTemplate:
        LaunchTemplateId: !Ref NetskopeInstanceTemplate
        Version: !GetAtt NetskopeInstanceTemplate.LatestVersionNumber
      MinSize: !Ref InstanceCount
      MaxSize: !Ref InstanceCount
      DesiredCapacity: !Ref InstanceCount
      Tags:
        - Key: Name
          Value: !Sub ${InstanceName}
          PropagateAtLaunch: true

Outputs:
  AutoScalingGroupName:
    Description: Name of the Auto Scaling Group
    Value: !Ref NetskopeAutoScalingGroup
  
  LaunchTemplateId:
    Description: ID of the Launch Template
    Value: !Ref NetskopeInstanceTemplate
  
  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref NetskopeSecurityGroup